[project]
name = "monocore_theme"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = ["frappe"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core:buildapi"

[tool.bench]
app-name = "monocore_theme"
