[project]
name = "monocore_theme"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = ["frappe"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.bench]
app-name = "monocore_theme"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0"
